FROM oven/bun:1.3.14-alpine

WORKDIR /app

COPY package.json bun.lock bunfig.toml tsconfig.json ./
COPY apps/ui/package.json ./apps/ui/package.json
COPY apps/control ./apps/control
COPY packages ./packages
COPY drizzle.config.ts ./

RUN bun install --frozen-lockfile --production --filter '!@proxycore/ui'

CMD ["bun", "run", "control"]
